### ISSUE TITLE
How is this library different?

### ISSUE THREAD

**Issue by tredondo** [coinsop/kraken-wrapper#1]
There were at least 2 other Kraken API wrapper libs when this one was created:

* https://github.com/lucklo/kraken-exchange-api
* https://github.com/nothingisdead/npm-kraken-api

It would be nice to credit @lucklo and @nothingisdead and explain how this library is different.

**Comment by lucklo** [comment]
Well unfortunately my implementation is really incomplete at this point - I kind of stopped because Kraken API was essentially unresponsive at the time. 
I'm happy that there are more implementations for Kraken API for simple reason - their API interface is terrible for "simple" operations. 
I would love to see Kraken's official node.js implementation in future.

**Comment by oliversd** [comment]
Hi @meteorpublish there are several libraries that connect with kraken.

We wanted to make a library for a project that have minimal dependencies and uses promises so we made this.

About the credit, this was made by us and have a MIT LICENSE. We use and recognize all the open source libraries out there and the people that give their time to the community, so for all that people goes the credit.
